#167164942 login in user
andela/dahlia-ah-frontend pull request #10
Opened 2019-08-29 17:01 UTC by benisi

## Pivotal tracker story
[#167164942](https://www.pivotaltracker.com/story/show/167164942) 
#### What does this PR do?
 Add user login functionality
#### Summary of Task
This PR adds the following to the project
 - add login functionality
 - add user context

#### How can this be tested?
```
# Clone this repository
$ git clone https://github.com/andela/dahlia-ah-frontend.git

# Navigate to the application folder
$ cd dahlia-ah-frontend

# Install dependencies
$ npm install

# start the server by typing
$ npm run dev

visit http://localhost:{port}/login

### Screenshots

2019-08-30 03:56 UTC, WilliamsOhworuka commented on src/components/MaroForm/MaroForm.js
> +import React, { useState } from 'react';
please consider changing file name

2019-08-30 17:01 UTC, Nkemjiks requested changes

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/App.js
> +      <Route path="/hello" component={HelloDahlia} />
Take out this dummy component

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/App.js
> +      <Route path="/login" component={Login} />
You don't need this route since its going to be a modal over the landing page

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/AuthModal/AuthModal.scss
> +.backdrop-div {
wrap this css in a parent css so it doesn't clash with other css

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/Aux/Aux.js
> +const Aux = (props) => (props.children);
What is this file for?

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/Form/Form.js
> +/* eslint-disable react/prop-types */
Change all react file file to use `jsx` not `js`

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/Login/Login.js
> +  const [display, setDisplay] = useState(true);
Move the state to a seperate js file.Let this file only be concerned with rendering

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/Login/Login.js
> +        <a href="abc">Sign Up</a>
Change this to an element that can take the onclick method and style properly

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/Login/Login.scss
> +.small-text {
Wrap this up in a parent class

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/LoginForm/LoginForm.js
> +  const { setUser } = useContext(UserContext);
Move all of this to a separate file

2019-08-30 17:01 UTC, Nkemjiks commented on src/components/MaroForm/MaroForm.js
> +  const [formdata, setFormData] = useState({
Move all this to a separate file

2019-09-02 08:03 UTC, benisi commented on src/components/Aux/Aux.js
> +const Aux = (props) => (props.children);
I will take it out, it was part of the files we were working on

2019-09-04 13:54 UTC, Nkemjiks approved these changes

2019-09-04 13:54 UTC, merged